// web/src/views/admin/SyncTasksView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Close, Refresh } from '@element-plus/icons-vue'
import {
  cancelSyncTask,
  listSyncTasks,
  purgeFinishedSyncTasks,
  retrySyncTask,
  type SyncTaskListParams,
} from '@/api/syncTasks'
import type { SyncTask, SyncTaskStatus, SyncTaskType } from '@/api/types'

const items = ref<SyncTask[]>([])
const total = ref(0)
const page = ref(1)
const pageSize = ref(50)
const loading = ref(false)
const statusFilter = ref<SyncTaskStatus | ''>('')
const typeFilter = ref<SyncTaskType | ''>('')
const selectedItems = ref<SyncTask[]>([])
const batchBusy = ref<'retry' | 'cancel' | ''>('')

const detailDialog = ref(false)
const detailRow = ref<SyncTask | null>(null)

const statusOptions: { label: string; value: SyncTaskStatus }[] = [
  { label: '等待中', value: 'pending' },
  { label: '执行中', value: 'running' },
  { label: '已成功', value: 'succeeded' },
  { label: '已取消', value: 'canceled' },
]

const typeOptions: { label: string; value: SyncTaskType }[] = [
  { label: '删除用户', value: 'user_delete' },
  { label: '同步用户节点', value: 'user_resync' },
  { label: '同步用户配置', value: 'user_push_config' },
  { label: '创建节点', value: 'node_create' },
  { label: '删除节点', value: 'node_delete' },
  { label: '同步节点启用', value: 'node_set_enabled' },
  { label: '更新节点配置', value: 'node_update' },
]

const pendingCount = computed(() => items.value.filter((row) => statusOf(row) === 'pending').length)
const selectedCount = computed(() => selectedItems.value.length)

function idOf(row: SyncTask) {
  return row.id ?? row.ID ?? 0
}

function typeOf(row: SyncTask) {
  return row.type ?? row.Type ?? ''
}

function statusOf(row: SyncTask) {
  return row.status ?? row.Status ?? ''
}

function summaryOf(row: SyncTask) {
  return row.summary ?? row.Summary ?? ''
}

function targetOf(row: SyncTask) {
  const typ = row.target_type ?? row.TargetType ?? ''
  const id = row.target_id ?? row.TargetID ?? ''
  return `${typ}#${id}`
}

function attemptsOf(row: SyncTask) {
  return row.attempts ?? row.Attempts ?? 0
}

function nextRunOf(row: SyncTask) {
  return row.next_run_at ?? row.NextRunAt
}

function lastErrorOf(row: SyncTask) {
  return row.last_error ?? row.LastError ?? ''
}

function statusTag(status: string) {
  if (status === 'succeeded') return 'success'
  if (status === 'running') return 'warning'
  if (status === 'canceled') return 'info'
  return 'danger'
}

function formatDate(value?: string | null) {
  if (!value) return '-'
  return new Date(value).toLocaleString()
}

async function load() {
  loading.value = true
  try {
    const params: SyncTaskListParams = {
      page: page.value,
      page_size: pageSize.value,
    }
    if (statusFilter.value) params.status = statusFilter.value
    if (typeFilter.value) params.type = typeFilter.value
    const res = await listSyncTasks(params)
    items.value = res.items
    total.value = res.total
    selectedItems.value = []
  } finally {
    loading.value = false
  }
}

function handleSelectionChange(rows: SyncTask[]) {
  selectedItems.value = rows
}

async function retry(row: SyncTask) {
  await retrySyncTask(idOf(row))
  await load()
}

async function cancel(row: SyncTask) {
  await cancelSyncTask(idOf(row))
  await load()
}

async function batchRetry() {
  if (selectedItems.value.length === 0) return
  const rows = selectedItems.value.slice()
  batchBusy.value = 'retry'
  try {
    const results = await Promise.allSettled(rows.map((row) => retrySyncTask(idOf(row))))
    const failed = results.filter((result) => result.status === 'rejected').length
    if (failed > 0) {
      ElMessage.warning(`已重试 ${rows.length - failed} 个任务，失败 ${failed} 个`)
    } else {
      ElMessage.success(`已重试 ${rows.length} 个任务`)
    }
    await load()
  } finally {
    batchBusy.value = ''
  }
}

async function batchCancel() {
  if (selectedItems.value.length === 0) return
  const rows = selectedItems.value.slice()
  try {
    await ElMessageBox.confirm(`确定中止选中的 ${rows.length} 个同步任务？`, '批量中止任务', {
      type: 'warning',
    })
  } catch {
    return
  }
  batchBusy.value = 'cancel'
  try {
    const results = await Promise.allSettled(rows.map((row) => cancelSyncTask(idOf(row))))
    const failed = results.filter((result) => result.status === 'rejected').length
    if (failed > 0) {
      ElMessage.warning(`已中止 ${rows.length - failed} 个任务，失败 ${failed} 个`)
    } else {
      ElMessage.success(`已中止 ${rows.length} 个任务`)
    }
    await load()
  } finally {
    batchBusy.value = ''
  }
}

function showDetail(row: SyncTask) {
  detailRow.value = row
  detailDialog.value = true
}

async function purgeFinished() {
  try {
    await ElMessageBox.confirm(
      '清空所有非进行中（已成功 / 已取消）的同步任务记录？等待中 / 执行中的任务不受影响。',
      '清空已完成任务',
      { type: 'warning', confirmButtonText: '清空', cancelButtonText: '取消' }
    )
    const res = await purgeFinishedSyncTasks()
    ElMessage.success(`已清空 ${res.deleted} 条记录`)
    await load()
  } catch (e) {
    if (e !== 'cancel') ElMessage.error('清空失败')
  }
}

onMounted(load)
</script>

<template>
  <div class="psp-page">
    <div class="psp-page-header">
      <div>
        <div class="psp-page-title">同步任务</div>
        <div class="task-subtitle">当前列表等待重试：{{ pendingCount }}</div>
      </div>
      <div style="display: flex; gap: 8px;">
        <el-button type="danger" plain @click="purgeFinished">一键清空</el-button>
        <el-button type="primary" @click="load">
          <el-icon><Refresh /></el-icon>
          刷新
        </el-button>
      </div>
    </div>

    <div class="psp-toolbar">
      <el-select v-model="statusFilter" clearable placeholder="状态" style="width: 150px" @change="load">
        <el-option v-for="s in statusOptions" :key="s.value" :label="s.label" :value="s.value" />
      </el-select>
      <el-select v-model="typeFilter" clearable placeholder="任务类型" style="width: 180px" @change="load">
        <el-option v-for="t in typeOptions" :key="t.value" :label="t.label" :value="t.value" />
      </el-select>
      <template v-if="selectedCount > 0">
        <el-divider direction="vertical" />
        <span class="selection-count">已选 {{ selectedCount }}</span>
        <el-button
          type="primary"
          plain
          :icon="Refresh"
          :loading="batchBusy === 'retry'"
          :disabled="batchBusy !== ''"
          @click="batchRetry"
        >
          批量重试
        </el-button>
        <el-button
          type="danger"
          plain
          :icon="Close"
          :loading="batchBusy === 'cancel'"
          :disabled="batchBusy !== ''"
          @click="batchCancel"
        >
          批量中止
        </el-button>
      </template>
    </div>

    <el-table v-loading="loading" :data="items" stripe @selection-change="handleSelectionChange">
      <el-table-column type="selection" width="48" />
      <el-table-column label="ID" width="80">
        <template #default="{ row }">{{ idOf(row) }}</template>
      </el-table-column>
      <el-table-column label="状态" width="110">
        <template #default="{ row }">
          <el-tag :type="statusTag(statusOf(row))">{{ statusOf(row) }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="类型" width="170">
        <template #default="{ row }">{{ typeOf(row) }}</template>
      </el-table-column>
      <el-table-column label="目标" width="130">
        <template #default="{ row }">{{ targetOf(row) }}</template>
      </el-table-column>
      <el-table-column label="摘要" min-width="220">
        <template #default="{ row }">{{ summaryOf(row) }}</template>
      </el-table-column>
      <el-table-column label="重试" width="80">
        <template #default="{ row }">{{ attemptsOf(row) }}</template>
      </el-table-column>
      <el-table-column label="下次执行" width="190">
        <template #default="{ row }">{{ formatDate(nextRunOf(row)) }}</template>
      </el-table-column>
      <el-table-column label="错误" min-width="260">
        <template #default="{ row }">
          <span class="error-text">{{ lastErrorOf(row) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="210" fixed="right">
        <template #default="{ row }">
          <el-button size="small" @click="showDetail(row)">详情</el-button>
          <el-button size="small" type="primary" plain @click="retry(row)">重试</el-button>
          <el-button size="small" type="danger" plain @click="cancel(row)">中止</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[20, 50, 100, 200]"
      layout="total, sizes, prev, pager, next"
      style="margin-top: 16px"
      @current-change="load"
      @size-change="load"
    />

    <el-dialog v-model="detailDialog" title="任务详情" width="720px" top="6vh">
      <pre v-if="detailRow" class="task-json">{{ JSON.stringify(detailRow, null, 2) }}</pre>
    </el-dialog>
  </div>
</template>

<style scoped>
.task-subtitle {
  margin-top: 6px;
  color: var(--text-muted);
  font-size: 13px;
}

.error-text {
  display: inline-block;
  max-width: 100%;
  color: #f56c6c;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  vertical-align: bottom;
}

.task-json {
  font-family: ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace;
  font-size: 12px;
  line-height: 1.55;
  background: var(--code-bg);
  color: var(--text-main);
  border: 1px solid var(--code-border);
  padding: 12px;
  border-radius: 8px;
  max-height: 520px;
  overflow: auto;
  white-space: pre;
  word-break: normal;
}

.selection-count {
  color: var(--text-muted);
  white-space: nowrap;
}
</style>

// web-react/src/views/admin/SyncTasksView.tsx
import { useEffect, useMemo, useState } from 'react'
import {
  Box,
  Button,
  Card,
  Checkbox,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  IconButton,
  MenuItem,
  Pagination,
  Select,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tooltip,
  Typography,
  useTheme,
} from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import DeleteIcon from '@mui/icons-material/DeleteOutline'
import VisibilityIcon from '@mui/icons-material/Visibility'
import CloseIcon from '@mui/icons-material/Close'
import ReplayIcon from '@mui/icons-material/Replay'
import { useTranslation } from 'react-i18next'

import {
  cancelSyncTask,
  listSyncTasks,
  purgeFinishedSyncTasks,
  retrySyncTask,
  type SyncTaskListParams,
} from '@/api/syncTasks'
import type { SyncTask, SyncTaskStatus, SyncTaskType } from '@/api/types'
import { confirm } from '@/components/ConfirmHost'
import { pushSnack } from '@/components/SnackbarHost'

const PAGE_SIZE = 50

const STATUSES: SyncTaskStatus[] = ['pending', 'running', 'succeeded', 'canceled']
const TYPES: SyncTaskType[] = [
  'user_delete', 'user_resync', 'user_push_config',
  'node_create', 'node_delete', 'node_set_enabled', 'node_update',
]

function idOf(r: SyncTask) { return r.id ?? r.ID ?? 0 }
function typeOf(r: SyncTask): SyncTaskType | '' { return (r.type ?? r.Type ?? '') as SyncTaskType | '' }
function statusOf(r: SyncTask): SyncTaskStatus | '' { return (r.status ?? r.Status ?? '') as SyncTaskStatus | '' }
function summaryOf(r: SyncTask) { return r.summary ?? r.Summary ?? '' }
function targetOf(r: SyncTask) {
  const ty = r.target_type ?? r.TargetType ?? ''
  const id = r.target_id ?? r.TargetID ?? ''
  return `${ty}#${id}`
}
function attemptsOf(r: SyncTask) { return r.attempts ?? r.Attempts ?? 0 }
function nextRunOf(r: SyncTask) { return r.next_run_at ?? r.NextRunAt }
function lastErrorOf(r: SyncTask) { return r.last_error ?? r.LastError ?? '' }

function formatDate(s?: string | null) {
  if (!s) return '-'
  const d = new Date(s)
  return Number.isNaN(d.getTime()) ? '-' : d.toLocaleString()
}

export default function SyncTasksView() {
  const theme = useTheme()
  const md = theme.palette.md
  const { t } = useTranslation(['admin', 'common'])

  const [items, setItems] = useState<SyncTask[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [statusFilter, setStatusFilter] = useState<SyncTaskStatus | ''>('')
  const [typeFilter, setTypeFilter] = useState<SyncTaskType | ''>('')
  const [selected, setSelected] = useState<Set<number>>(new Set())
  const [batchBusy, setBatchBusy] = useState<'retry' | 'cancel' | ''>('')

  const [detailOpen, setDetailOpen] = useState(false)
  const [detail, setDetail] = useState<SyncTask | null>(null)

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const pendingCount = useMemo(() => items.filter(r => statusOf(r) === 'pending').length, [items])

  useEffect(() => { void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, statusFilter, typeFilter])

  async function load() {
    setLoading(true)
    try {
      const params: SyncTaskListParams = { page, page_size: PAGE_SIZE }
      if (statusFilter) params.status = statusFilter
      if (typeFilter) params.type = typeFilter
      const res = await listSyncTasks(params)
      setItems(res.items); setTotal(res.total); setSelected(new Set())
    } finally { setLoading(false) }
  }

  function toggleAll(checked: boolean) {
    setSelected(checked ? new Set(items.map(idOf)) : new Set())
  }
  function toggleOne(id: number, checked: boolean) {
    setSelected(prev => {
      const next = new Set(prev)
      if (checked) next.add(id); else next.delete(id)
      return next
    })
  }

  async function retry(r: SyncTask) { await retrySyncTask(idOf(r)); await load() }
  async function cancel(r: SyncTask) { await cancelSyncTask(idOf(r)); await load() }

  async function batchRetry() {
    const rows = items.filter(r => selected.has(idOf(r)))
    if (!rows.length) return
    setBatchBusy('retry')
    try {
      const results = await Promise.allSettled(rows.map(r => retrySyncTask(idOf(r))))
      const failed = results.filter(r => r.status === 'rejected').length
      if (failed > 0) pushSnack(t('admin:sync_tasks.toast.batch_partial', { ok: rows.length - failed, fail: failed }), 'warning')
      else pushSnack(t('admin:sync_tasks.toast.batch_retried', { count: rows.length }), 'success')
      await load()
    } finally { setBatchBusy('') }
  }

  async function batchCancel() {
    const rows = items.filter(r => selected.has(idOf(r)))
    if (!rows.length) return
    const ok = await confirm({
      title: t('admin:sync_tasks.confirm.batch_cancel_title'),
      message: t('admin:sync_tasks.confirm.batch_cancel_message', { count: rows.length }),
      destructive: true,
    })
    if (!ok) return
    setBatchBusy('cancel')
    try {
      const results = await Promise.allSettled(rows.map(r => cancelSyncTask(idOf(r))))
      const failed = results.filter(r => r.status === 'rejected').length
      if (failed > 0) pushSnack(t('admin:sync_tasks.toast.batch_partial', { ok: rows.length - failed, fail: failed }), 'warning')
      else pushSnack(t('admin:sync_tasks.toast.batch_canceled', { count: rows.length }), 'success')
      await load()
    } finally { setBatchBusy('') }
  }

  async function purge() {
    const ok = await confirm({
      title: t('admin:sync_tasks.confirm.purge_title'),
      message: t('admin:sync_tasks.confirm.purge_message'),
      destructive: true,
      confirmText: t('admin:sync_tasks.purge'),
    })
    if (!ok) return
    const res = await purgeFinishedSyncTasks()
    pushSnack(t('admin:sync_tasks.toast.purged', { count: res.deleted }), 'success')
    await load()
  }

  function statusBadge(s: SyncTaskStatus | '') {
    let bg = md.surfaceContainerHighest, fg = md.onSurfaceVariant
    if (s === 'succeeded') { bg = md.tertiaryContainer; fg = md.onTertiaryContainer }
    else if (s === 'running') { bg = md.secondaryContainer; fg = md.onSecondaryContainer }
    else if (s === 'pending') { bg = md.primaryContainer; fg = md.onPrimaryContainer }
    else if (s === 'canceled') { bg = md.surfaceContainerHighest; fg = md.onSurfaceVariant }
    return <Box sx={{
      display: 'inline-block', px: 1.25, py: 0.25,
      borderRadius: 1, fontSize: 12, fontWeight: 500,
      bgcolor: bg, color: fg, whiteSpace: 'nowrap',
    }}>{s ? t(`admin:sync_tasks.status.${s}`) : '-'}</Box>
  }

  const allChecked = items.length > 0 && items.every(r => selected.has(idOf(r)))
  const someChecked = selected.size > 0 && !allChecked

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 2, mb: 1 }}>
        <Box>
          <Typography variant="h4">{t('admin:sync_tasks.title')}</Typography>
          <Typography variant="body2" sx={{ mt: 0.5 }}>
            {t('admin:sync_tasks.pending_count', { count: pendingCount })}
          </Typography>
        </Box>
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Button variant="outlined" color="error" onClick={purge}>{t('admin:sync_tasks.purge')}</Button>
          <Button variant="contained" startIcon={<RefreshIcon />} onClick={() => load()}>
            {t('admin:sync_tasks.refresh')}
          </Button>
        </Box>
      </Box>

      <Box sx={{ display: 'flex', gap: 1.5, mb: 2, flexWrap: 'wrap', alignItems: 'center' }}>
        <Select size="small" value={statusFilter} displayEmpty
          onChange={e => { setStatusFilter(e.target.value as SyncTaskStatus | ''); setPage(1) }}
          sx={{ minWidth: 150, height: 40 }}>
          <MenuItem value="">{t('admin:sync_tasks.filter_status')}</MenuItem>
          {STATUSES.map(s => <MenuItem key={s} value={s}>{t(`admin:sync_tasks.status.${s}`)}</MenuItem>)}
        </Select>
        <Select size="small" value={typeFilter} displayEmpty
          onChange={e => { setTypeFilter(e.target.value as SyncTaskType | ''); setPage(1) }}
          sx={{ minWidth: 180, height: 40 }}>
          <MenuItem value="">{t('admin:sync_tasks.filter_type')}</MenuItem>
          {TYPES.map(ty => <MenuItem key={ty} value={ty}>{t(`admin:sync_tasks.type.${ty}`)}</MenuItem>)}
        </Select>
        {selected.size > 0 && (
          <Box sx={{
            display: 'flex', alignItems: 'center', gap: 1, ml: 1, px: 2, py: 1,
            borderRadius: 9999, bgcolor: md.secondaryContainer, color: md.onSecondaryContainer,
          }}>
            <Typography sx={{ fontSize: 13, fontWeight: 500, mr: 1 }}>
              {t('admin:sync_tasks.selection_count', { count: selected.size })}
            </Typography>
            <Button size="small" variant="text" sx={{ color: 'inherit' }}
              startIcon={batchBusy === 'retry' ? <CircularProgress size={14} /> : <ReplayIcon />}
              disabled={batchBusy !== ''} onClick={batchRetry}>
              {t('admin:sync_tasks.batch_retry')}
            </Button>
            <Button size="small" variant="text" color="error"
              startIcon={batchBusy === 'cancel' ? <CircularProgress size={14} /> : <CloseIcon />}
              disabled={batchBusy !== ''} onClick={batchCancel}>
              {t('admin:sync_tasks.batch_cancel')}
            </Button>
          </Box>
        )}
      </Box>

      <Card sx={{ bgcolor: md.surfaceContainerLow, boxShadow: '0 1px 2px rgba(0,0,0,.3),0 1px 3px 1px rgba(0,0,0,.15)', overflow: 'hidden' }}>
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow sx={{ '& th': { color: md.onSurfaceVariant, fontWeight: 500, fontSize: 12, textTransform: 'uppercase', letterSpacing: '.5px', borderBottom: `1px solid ${md.outlineVariant}`, whiteSpace: 'nowrap' } }}>
                <TableCell padding="checkbox">
                  <Checkbox indeterminate={someChecked} checked={allChecked}
                    onChange={(_, c) => toggleAll(c)} disabled={items.length === 0} />
                </TableCell>
                <TableCell>{t('admin:sync_tasks.table.id')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.status')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.type')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.target')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.summary')}</TableCell>
                <TableCell align="right">{t('admin:sync_tasks.table.attempts')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.next_run')}</TableCell>
                <TableCell>{t('admin:sync_tasks.table.error')}</TableCell>
                <TableCell align="right">{t('admin:sync_tasks.table.actions')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {loading && items.length === 0 && (
                <TableRow><TableCell colSpan={10} sx={{ textAlign: 'center', py: 6 }}><CircularProgress size={24} /></TableCell></TableRow>
              )}
              {!loading && items.length === 0 && (
                <TableRow><TableCell colSpan={10} sx={{ textAlign: 'center', py: 6, color: md.onSurfaceVariant }}>—</TableCell></TableRow>
              )}
              {items.map(r => {
                const id = idOf(r); const ty = typeOf(r); const err = lastErrorOf(r)
                return (
                  <TableRow key={id} hover sx={{ '& td': { borderBottom: `1px solid ${md.outlineVariant}`, whiteSpace: 'nowrap' } }}>
                    <TableCell padding="checkbox">
                      <Checkbox checked={selected.has(id)} onChange={(_, c) => toggleOne(id, c)} />
                    </TableCell>
                    <TableCell sx={{ fontSize: 13, color: md.onSurfaceVariant }}>{id}</TableCell>
                    <TableCell>{statusBadge(statusOf(r))}</TableCell>
                    <TableCell sx={{ fontSize: 13 }}>{ty ? t(`admin:sync_tasks.type.${ty}`) : '-'}</TableCell>
                    <TableCell sx={{ fontSize: 13 }}>{targetOf(r)}</TableCell>
                    <TableCell sx={{ fontSize: 13, maxWidth: 280, overflow: 'hidden', textOverflow: 'ellipsis' }}>{summaryOf(r)}</TableCell>
                    <TableCell align="right" sx={{ fontVariantNumeric: 'tabular-nums' }}>{attemptsOf(r)}</TableCell>
                    <TableCell sx={{ fontSize: 13 }}>{formatDate(nextRunOf(r))}</TableCell>
                    <TableCell sx={{ fontSize: 12, color: md.error, maxWidth: 280, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      <Tooltip title={err}><span>{err}</span></Tooltip>
                    </TableCell>
                    <TableCell align="right">
                      <Tooltip title={t('admin:sync_tasks.action.detail')}>
                        <IconButton size="small" onClick={() => { setDetail(r); setDetailOpen(true) }}>
                          <VisibilityIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                      <Tooltip title={t('admin:sync_tasks.action.retry')}>
                        <IconButton size="small" onClick={() => retry(r)}><ReplayIcon fontSize="small" /></IconButton>
                      </Tooltip>
                      <Tooltip title={t('admin:sync_tasks.action.cancel')}>
                        <IconButton size="small" onClick={() => cancel(r)} sx={{ color: md.error }}>
                          <CloseIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </TableCell>
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </TableContainer>
        {totalPages > 1 && (
          <Box sx={{ display: 'flex', justifyContent: 'center', py: 2, borderTop: `1px solid ${md.outlineVariant}` }}>
            <Pagination count={totalPages} page={page} onChange={(_, p) => setPage(p)} shape="rounded" color="primary" />
          </Box>
        )}
      </Card>

      {/* Detail dialog */}
      <Dialog open={detailOpen} onClose={() => setDetailOpen(false)}
        PaperProps={{ sx: { borderRadius: 3, bgcolor: md.surfaceContainerHigh, width: 720, maxWidth: '95vw' } }}>
        <DialogTitle>{t('admin:sync_tasks.detail_title')} #{detail && idOf(detail)}</DialogTitle>
        <DialogContent>
          {detail && (
            <Box component="pre" sx={{
              p: 2, bgcolor: md.surfaceContainerHighest, borderRadius: 1.5,
              fontSize: 13, lineHeight: 1.55, color: md.onSurface,
              // <pre> defaults to the browser's old Courier New on Windows,
              // which looks cramped and ragged. Stack modern monospaces so we
              // pick whatever the OS / app actually ships first.
              fontFamily: `ui-monospace, "SF Mono", "Cascadia Code", "JetBrains Mono", Menlo, Consolas, "Liberation Mono", monospace`,
              overflow: 'auto', maxHeight: 520, m: 0,
              tabSize: 2,
            }}>
              {JSON.stringify(detail, null, 2)}
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <DeleteIcon sx={{ display: 'none' }} />
          <Button variant="contained" onClick={() => setDetailOpen(false)}>{t('common:actions.ok')}</Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
