// web/src/views/admin/TemplatesView.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete } from '@element-plus/icons-vue'
import { deleteTemplate, listTemplates, saveTemplate, type Template } from '@/api/templates'
import { listRuleSets, type RuleSet } from '@/api/rules'

const items = ref<Template[]>([])
const ruleSets = ref<RuleSet[]>([])
const loading = ref(false)
const selectedItems = ref<Template[]>([])
const batchBusy = ref(false)
const selectedCount = computed(() => selectedItems.value.length)
const dialog = ref(false)
const editing = ref(false)
const form = reactive<Template>({
  slug: '',
  name: '',
  client_type: 'mihomo',
  is_default: false,
  rule_sets: [],
  content: '',
})

const builtInTargets = new Set(['DIRECT', 'REJECT', 'REJECT-DROP', 'REJECT-DROP-BIT', 'PASS'])

const selectedRuleSetDetails = computed(() =>
  form.rule_sets
    .map((slug) => ruleSets.value.find((item) => item.slug === slug))
    .filter((item): item is RuleSet => Boolean(item)),
)

const formProxyGroups = computed(() => extractProxyGroups(form.content))
const formRuleTargets = computed(() => extractRuleTargets(selectedRuleSetDetails.value))
const formMissingTargets = computed(() => missingTargets(formProxyGroups.value, formRuleTargets.value))
const formDynamicProxyGroups = computed(() => usesDynamicProxyGroups(form.content))

async function load() {
  loading.value = true
  try {
    const [templateItems, ruleSetItems] = await Promise.all([listTemplates(), listRuleSets()])
    items.value = templateItems
    ruleSets.value = ruleSetItems
    selectedItems.value = []
  } finally {
    loading.value = false
  }
}

function handleSelectionChange(rows: Template[]) {
  selectedItems.value = rows
}

function canSelectTemplate(row: Template) {
  return !row.is_default
}

function openCreate() {
  editing.value = false
  form.slug = ''
  form.name = ''
  form.client_type = 'mihomo'
  form.is_default = false
  form.rule_sets = []
  form.content = ''
  dialog.value = true
}

function openEdit(t: Template) {
  editing.value = true
  form.slug = t.slug
  form.name = t.name
  form.client_type = t.client_type
  form.is_default = t.is_default
  form.rule_sets = t.rule_sets ? t.rule_sets.slice() : []
  form.content = t.content
  dialog.value = true
}

function ruleSetName(slug: string) {
  return ruleSets.value.find((item) => item.slug === slug)?.name || slug
}

function ruleSetSummary(row: Template) {
  if (!row.rule_sets || row.rule_sets.length === 0) return '未绑定'
  return row.rule_sets.map(ruleSetName).join('、')
}

function templateRuleSets(row: Template) {
  return (row.rule_sets || [])
    .map((slug) => ruleSets.value.find((item) => item.slug === slug))
    .filter((item): item is RuleSet => Boolean(item))
}

function normalizeTarget(raw: string) {
  return raw.trim().replace(/^['"]|['"]$/g, '')
}

function extractProxyGroups(content: string) {
  const groups = new Set<string>()
  let inProxyGroups = false
  for (const line of content.split('\n')) {
    if (/^proxy-groups\s*:/.test(line)) {
      inProxyGroups = true
      continue
    }
    if (inProxyGroups && /^\S/.test(line) && !/^proxy-groups\s*:/.test(line)) {
      break
    }
    const match = line.match(/^\s*-\s*name:\s*(.+?)\s*$/)
    if (inProxyGroups && match) {
      groups.add(normalizeTarget(match[1]))
    }
  }
  return groups
}

function usesDynamicProxyGroups(content: string) {
  return /\{\{\s*proxy_groups\s*\}\}/.test(content)
}

function extractRuleTargets(sets: RuleSet[]) {
  const targets = new Set<string>()
  for (const rs of sets) {
    if (!rs.enabled) continue
    for (const rawLine of rs.content.split('\n')) {
      const line = rawLine.trim().replace(/^-\s*/, '')
      if (!line || line.startsWith('#') || line.includes('{{')) continue
      const parts = line.split(',').map((part) => normalizeTarget(part))
      if (parts.length < 2) continue
      const usefulParts = parts.filter((part) => part && part !== 'no-resolve')
      const target = usefulParts[usefulParts.length - 1]
      if (target && !builtInTargets.has(target)) {
        targets.add(target)
      }
    }
  }
  return targets
}

function missingTargets(groups: Set<string>, targets: Set<string>) {
  if (groups.size === 0) return Array.from(targets)
  return Array.from(targets).filter((target) => !groups.has(target))
}

function coverageState(row: Template) {
  const sets = templateRuleSets(row)
  if (sets.length === 0) return { type: 'info', text: '未绑定' }
  if (usesDynamicProxyGroups(row.content)) return { type: 'success', text: '自动生成' }
  const groups = extractProxyGroups(row.content)
  const missing = missingTargets(groups, extractRuleTargets(sets))
  if (missing.length > 0) return { type: 'warning', text: `缺失 ${missing.length}` }
  return { type: 'success', text: '正常' }
}

async function submit() {
  if (!form.slug || !form.name) {
    ElMessage.warning('slug 和 name 必填')
    return
  }
  await saveTemplate({ ...form })
  ElMessage.success('已保存')
  dialog.value = false
  await load()
}

async function confirmDelete(t: Template) {
  await ElMessageBox.confirm(`删除配置方案 ${t.slug}？`, '确认', { type: 'warning' })
  await deleteTemplate(t.slug)
  ElMessage.success('已删除')
  await load()
}

async function batchDelete() {
  if (selectedItems.value.length === 0) return
  const rows = selectedItems.value.slice()
  const names = rows.slice(0, 5).map((row) => row.slug).join('、')
  const suffix = rows.length > 5 ? ` 等 ${rows.length} 个配置方案` : ''
  try {
    await ElMessageBox.confirm(`确定删除 ${names}${suffix}？`, '批量删除配置方案', { type: 'warning' })
  } catch {
    return
  }
  batchBusy.value = true
  try {
    const results = await Promise.allSettled(rows.map((row) => deleteTemplate(row.slug)))
    const deletedRows = rows.filter((_, index) => results[index].status === 'fulfilled')
    const failed = rows.length - deletedRows.length
    items.value = items.value.filter((item) => !deletedRows.some((row) => row.slug === item.slug))
    selectedItems.value = []
    if (failed > 0) {
      ElMessage.warning(`已删除 ${deletedRows.length} 个配置方案，失败 ${failed} 个`)
    } else {
      ElMessage.success(`已删除 ${deletedRows.length} 个配置方案`)
    }
  } finally {
    batchBusy.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="psp-page">
    <div class="psp-page-header">
      <div>
        <div class="psp-page-title">配置方案</div>
        <div class="psp-page-desc">一个方案由客户端模板和绑定规则集组成，订阅渲染会以这里的绑定为准。</div>
      </div>
      <el-button type="primary" @click="openCreate">新增方案</el-button>
    </div>

    <div v-if="selectedCount > 0" class="psp-toolbar">
      <span class="selection-count">已选 {{ selectedCount }}</span>
      <el-button
        type="danger"
        :icon="Delete"
        :loading="batchBusy"
        @click="batchDelete"
      >
        批量删除
      </el-button>
    </div>

    <el-table v-loading="loading" :data="items" stripe @selection-change="handleSelectionChange">
      <el-table-column type="selection" width="48" :selectable="canSelectTemplate" />
      <el-table-column prop="slug" label="Slug" min-width="160" />
      <el-table-column prop="name" label="名称" min-width="180" />
      <el-table-column prop="client_type" label="客户端" width="140" />
      <el-table-column label="规则集" min-width="220" show-overflow-tooltip>
        <template #default="{ row }">{{ ruleSetSummary(row) }}</template>
      </el-table-column>
      <el-table-column label="规则目标" width="110">
        <template #default="{ row }">
          <el-tag :type="coverageState(row).type" size="small">{{ coverageState(row).text }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="默认" width="80">
        <template #default="{ row }">
          <el-tag v-if="row.is_default" type="success" size="small">默认</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200">
        <template #default="{ row }">
          <el-button size="small" @click="openEdit(row)">编辑</el-button>
          <el-button size="small" type="danger" @click="confirmDelete(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      v-model="dialog"
      :title="editing ? '编辑配置方案' : '新增配置方案'"
      width="900px"
      top="4vh"
    >
      <el-form label-width="100px">
        <el-form-item label="Slug" required>
          <el-input v-model="form.slug" :disabled="editing" />
        </el-form-item>
        <el-form-item label="名称" required>
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="客户端类型">
          <el-select v-model="form.client_type" style="width: 200px">
            <el-option label="mihomo" value="mihomo" />
            <el-option label="Sing-box" value="sing-box" />
          </el-select>
        </el-form-item>
        <el-form-item label="设为默认">
          <el-switch v-model="form.is_default" />
        </el-form-item>
        <el-form-item label="规则集">
          <el-select
            v-model="form.rule_sets"
            multiple
            clearable
            filterable
            collapse-tags
            collapse-tags-tooltip
            placeholder="选择与该模板策略组匹配的规则集"
            style="width: 100%"
          >
            <el-option
              v-for="ruleSet in ruleSets"
              :key="ruleSet.slug"
              :label="`${ruleSet.name} (${ruleSet.slug})`"
              :value="ruleSet.slug"
              :disabled="!ruleSet.enabled"
            />
          </el-select>
          <div class="form-hint">订阅渲染只使用这里绑定的规则集；未绑定时 <code v-pre>{{ rules_common }}</code> 为空。模板可用 <code v-pre>{{ proxy_groups }}</code> 让策略组跟随规则目标自动生成。</div>
          <div v-if="form.rule_sets.length > 0" class="binding-summary">
            <el-tag
              v-for="ruleSet in selectedRuleSetDetails"
              :key="ruleSet.slug"
              :type="ruleSet.enabled ? 'success' : 'info'"
              size="small"
            >
              {{ ruleSet.name }}
            </el-tag>
          </div>
          <div v-if="formDynamicProxyGroups && form.rule_sets.length > 0" class="target-ok">
            策略组将根据已绑定规则集的规则目标自动生成。
          </div>
          <div v-else-if="formMissingTargets.length > 0" class="target-warning">
            规则目标未在模板策略组中找到：{{ formMissingTargets.slice(0, 8).join('、') }}{{ formMissingTargets.length > 8 ? ` 等 ${formMissingTargets.length} 个` : '' }}
          </div>
          <div v-else-if="form.rule_sets.length > 0" class="target-ok">
            已识别 {{ formProxyGroups.size }} 个策略组，规则目标匹配正常。
          </div>
          <div v-else class="target-empty">
            当前未绑定规则集，只会渲染节点、策略组和个人规则。
          </div>
        </el-form-item>
        <el-form-item label="模板内容">
          <el-input
            v-model="form.content"
            type="textarea"
            :rows="22"
            placeholder="支持 {{ proxies }} / {{ proxy_groups }} / {{ rules_common }} / {{ rules_personal }} / @all / @region:TW 等占位符"
            class="psp-yaml-editor"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialog = false">取消</el-button>
        <el-button type="primary" @click="submit">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<style scoped>
.psp-yaml-editor :deep(textarea) {
  font-family: ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace;
  font-size: 13px;
  line-height: 1.5;
}

.selection-count {
  color: var(--text-muted);
  white-space: nowrap;
}

.psp-page-desc {
  margin-top: 6px;
  color: var(--text-muted);
  font-size: 13px;
}

.form-hint {
  margin-top: 6px;
  color: var(--text-muted);
  font-size: 12px;
  line-height: 1.4;
}

.binding-summary {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 8px;
}

.target-warning,
.target-ok,
.target-empty {
  margin-top: 8px;
  font-size: 12px;
  line-height: 1.5;
}

.target-warning {
  color: var(--el-color-warning);
}

.target-ok {
  color: var(--el-color-success);
}

.target-empty {
  color: var(--text-muted);
}
</style>

// web-react/src/views/admin/TemplatesView.tsx
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import {
  Box,
  Button,
  Card,
  Checkbox,
  Chip,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  FormControlLabel,
  IconButton,
  InputLabel,
  ListItemText,
  MenuItem,
  OutlinedInput,
  Select,
  Switch,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Tooltip,
  Typography,
  useTheme,
} from '@mui/material'
import AddIcon from '@mui/icons-material/Add'
import DeleteIcon from '@mui/icons-material/DeleteOutline'
import EditIcon from '@mui/icons-material/EditOutlined'
import { useTranslation } from 'react-i18next'

import { deleteTemplate, listTemplates, saveTemplate, type Template } from '@/api/templates'
import { listRuleSets, type RuleSet } from '@/api/rules'
import { confirm } from '@/components/ConfirmHost'
import { pushSnack } from '@/components/SnackbarHost'

const EMPTY: Template = {
  slug: '', name: '', client_type: 'mihomo', is_default: false, rule_sets: [], content: '',
}

const BUILTIN_TARGETS = new Set(['DIRECT', 'REJECT', 'REJECT-DROP', 'REJECT-DROP-BIT', 'PASS'])

function normalizeTarget(raw: string) { return raw.trim().replace(/^['"]|['"]$/g, '') }

function extractProxyGroups(content: string): Set<string> {
  const groups = new Set<string>()
  let inProxyGroups = false
  for (const line of content.split('\n')) {
    if (/^proxy-groups\s*:/.test(line)) { inProxyGroups = true; continue }
    if (inProxyGroups && /^\S/.test(line) && !/^proxy-groups\s*:/.test(line)) break
    const match = line.match(/^\s*-\s*name:\s*(.+?)\s*$/)
    if (inProxyGroups && match) groups.add(normalizeTarget(match[1]))
  }
  return groups
}

function usesDynamicProxyGroups(content: string) {
  return /\{\{\s*proxy_groups\s*\}\}/.test(content) || /\{\{\s*outbounds\s*\}\}/.test(content)
}

function extractRuleTargets(sets: RuleSet[]): Set<string> {
  const targets = new Set<string>()
  for (const rs of sets) {
    if (!rs.enabled) continue
    for (const rawLine of rs.content.split('\n')) {
      const line = rawLine.trim().replace(/^-\s*/, '')
      if (!line || line.startsWith('#') || line.includes('{{')) continue
      const parts = line.split(',').map(p => normalizeTarget(p))
      if (parts.length < 2) continue
      const useful = parts.filter(p => p && p !== 'no-resolve')
      const target = useful[useful.length - 1]
      if (target && !BUILTIN_TARGETS.has(target)) targets.add(target)
    }
  }
  return targets
}

function missingTargets(groups: Set<string>, targets: Set<string>): string[] {
  if (groups.size === 0) return Array.from(targets)
  return Array.from(targets).filter(t => !groups.has(t))
}

export default function TemplatesView() {
  const theme = useTheme()
  const md = theme.palette.md
  const { t } = useTranslation(['admin', 'common'])

  const [items, setItems] = useState<Template[]>([])
  const [ruleSets, setRuleSets] = useState<RuleSet[]>([])
  const [loading, setLoading] = useState(false)
  const [selected, setSelected] = useState<Set<string>>(new Set())
  const [batchBusy, setBatchBusy] = useState(false)

  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState(false)
  const [form, setForm] = useState<Template>(EMPTY)
  const [busy, setBusy] = useState(false)

  const selectableSlugs = items.filter(i => !i.is_default).map(i => i.slug)
  const allChecked = selectableSlugs.length > 0 && selectableSlugs.every(s => selected.has(s))
  const someChecked = selected.size > 0 && !allChecked

  const ruleSetMap = useMemo(() => new Map(ruleSets.map(r => [r.slug, r])), [ruleSets])

  useEffect(() => { void load() }, [])

  async function load() {
    setLoading(true)
    try {
      const [tpls, rules] = await Promise.all([listTemplates(), listRuleSets()])
      setItems(tpls); setRuleSets(rules); setSelected(new Set())
    } finally { setLoading(false) }
  }

  function toggleAll(checked: boolean) {
    setSelected(checked ? new Set(selectableSlugs) : new Set())
  }
  function toggleOne(slug: string, checked: boolean) {
    setSelected(prev => {
      const next = new Set(prev)
      if (checked) next.add(slug); else next.delete(slug)
      return next
    })
  }

  function openCreate() { setEditing(false); setForm(EMPTY); setDialogOpen(true) }
  function openEdit(tpl: Template) {
    setEditing(true)
    setForm({ ...tpl, rule_sets: tpl.rule_sets ? [...tpl.rule_sets] : [] })
    setDialogOpen(true)
  }

  async function submit(e: FormEvent) {
    e.preventDefault()
    if (!form.slug || !form.name) {
      pushSnack(t('admin:templates.validate.slug_name_required'), 'warning'); return
    }
    setBusy(true)
    try {
      await saveTemplate({ ...form })
      pushSnack(t('admin:templates.toast.saved'), 'success')
      setDialogOpen(false)
      await load()
    } finally { setBusy(false) }
  }

  async function confirmDelete(tpl: Template) {
    const ok = await confirm({
      title: t('admin:templates.confirm.delete_title'),
      message: t('admin:templates.confirm.delete_message', { slug: tpl.slug }),
      destructive: true,
    })
    if (!ok) return
    await deleteTemplate(tpl.slug)
    pushSnack(t('admin:templates.toast.deleted'), 'success')
    await load()
  }

  async function batchDelete() {
    const rows = items.filter(i => selected.has(i.slug))
    if (!rows.length) return
    const ok = await confirm({
      title: t('admin:templates.confirm.batch_delete_title'),
      message: t('admin:templates.confirm.batch_delete_message', { count: rows.length }),
      destructive: true,
    })
    if (!ok) return
    setBatchBusy(true)
    try {
      const results = await Promise.allSettled(rows.map(r => deleteTemplate(r.slug)))
      const okSlugs = rows.filter((_, i) => results[i].status === 'fulfilled').map(r => r.slug)
      const failed = rows.length - okSlugs.length
      setItems(prev => prev.filter(x => !okSlugs.includes(x.slug)))
      setSelected(new Set())
      if (failed > 0) pushSnack(t('admin:templates.toast.batch_partial', { ok: okSlugs.length, fail: failed }), 'warning')
      else pushSnack(t('admin:templates.toast.batch_deleted', { count: okSlugs.length }), 'success')
    } finally { setBatchBusy(false) }
  }

  function ruleSetSummary(tpl: Template): string {
    if (!tpl.rule_sets?.length) return t('admin:templates.status.no_binding')
    return tpl.rule_sets.map(s => ruleSetMap.get(s)?.name || s).join('、')
  }

  function coverageBadge(tpl: Template) {
    const sets = (tpl.rule_sets || []).map(s => ruleSetMap.get(s)).filter((x): x is RuleSet => Boolean(x))
    if (sets.length === 0) return badge(t('admin:templates.status.no_binding'), md.surfaceContainerHighest, md.onSurfaceVariant)
    if (usesDynamicProxyGroups(tpl.content)) return badge(t('admin:templates.status.auto_generated'), md.tertiaryContainer, md.onTertiaryContainer)
    const groups = extractProxyGroups(tpl.content)
    const missing = missingTargets(groups, extractRuleTargets(sets))
    if (missing.length > 0) return badge(t('admin:templates.status.missing_n', { n: missing.length }), md.errorContainer, md.onErrorContainer)
    return badge(t('admin:templates.status.ok'), md.tertiaryContainer, md.onTertiaryContainer)
  }

  function badge(label: string, bg: string, fg: string) {
    return <Box sx={{
      display: 'inline-block', px: 1.25, py: 0.25,
      borderRadius: 1, fontSize: 12, fontWeight: 500,
      bgcolor: bg, color: fg, whiteSpace: 'nowrap',
    }}>{label}</Box>
  }

  // Form analysis
  const formSelectedRuleSets = form.rule_sets.map(s => ruleSetMap.get(s)).filter((x): x is RuleSet => Boolean(x))
  const formProxyGroups = extractProxyGroups(form.content)
  const formRuleTargets = extractRuleTargets(formSelectedRuleSets)
  const formMissing = missingTargets(formProxyGroups, formRuleTargets)
  const formDynamic = usesDynamicProxyGroups(form.content)

  function formHint() {
    if (formDynamic && form.rule_sets.length > 0) {
      return { color: md.tertiary, text: t('admin:templates.hint.auto_groups') }
    }
    if (formMissing.length > 0 && form.content.length > 50) {
      return {
        color: md.error,
        text: t('admin:templates.hint.missing_targets', {
          names: formMissing.slice(0, 8).join('、') + (formMissing.length > 8 ? ` +${formMissing.length - 8}` : ''),
        }),
      }
    }
    if (form.rule_sets.length > 0 && formProxyGroups.size > 0) {
      return { color: md.tertiary, text: t('admin:templates.hint.groups_ok', { n: formProxyGroups.size }) }
    }
    if (form.rule_sets.length === 0) {
      return { color: md.onSurfaceVariant, text: t('admin:templates.hint.no_binding') }
    }
    if (form.content.length < 50) {
      return { color: md.onSurfaceVariant, text: t('admin:templates.hint.incomplete') }
    }
    return null
  }
  const hint = formHint()

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 2, mb: 1 }}>
        <Box>
          <Typography variant="h4">{t('admin:templates.title')}</Typography>
          <Typography variant="body2" sx={{ mt: 0.5 }}>{t('admin:templates.subtitle')}</Typography>
        </Box>
        <Button variant="contained" startIcon={<AddIcon />} onClick={openCreate}>
          {t('admin:templates.create')}
        </Button>
      </Box>

      {selected.size > 0 && (
        <Box sx={{
          display: 'flex', alignItems: 'center', gap: 1, mt: 2, mb: 1, px: 2, py: 1,
          borderRadius: 9999, bgcolor: md.secondaryContainer, color: md.onSecondaryContainer,
          width: 'fit-content',
        }}>
          <Typography sx={{ fontSize: 13, fontWeight: 500, mr: 1 }}>
            {t('admin:templates.selection_count', { count: selected.size })}
          </Typography>
          <Button size="small" variant="text" color="error"
            startIcon={batchBusy ? <CircularProgress size={14} /> : <DeleteIcon />}
            disabled={batchBusy} onClick={batchDelete}>
            {t('admin:templates.batch_delete')}
          </Button>
        </Box>
      )}

      <Card sx={{ mt: 2, bgcolor: md.surfaceContainerLow, boxShadow: '0 1px 2px rgba(0,0,0,.3),0 1px 3px 1px rgba(0,0,0,.15)', overflow: 'hidden' }}>
        <TableContainer>
          <Table>
            <TableHead>
              <TableRow sx={{ '& th': { color: md.onSurfaceVariant, fontWeight: 500, fontSize: 12, textTransform: 'uppercase', letterSpacing: '.5px', borderBottom: `1px solid ${md.outlineVariant}`, whiteSpace: 'nowrap' } }}>
                <TableCell padding="checkbox">
                  <Checkbox indeterminate={someChecked} checked={allChecked}
                    onChange={(_, c) => toggleAll(c)} disabled={selectableSlugs.length === 0} />
                </TableCell>
                <TableCell>{t('admin:templates.table.slug')}</TableCell>
                <TableCell>{t('admin:templates.table.name')}</TableCell>
                <TableCell>{t('admin:templates.table.client_type')}</TableCell>
                <TableCell>{t('admin:templates.table.rule_sets')}</TableCell>
                <TableCell>{t('admin:templates.table.coverage')}</TableCell>
                <TableCell>{t('admin:templates.table.default')}</TableCell>
                <TableCell align="right">{t('admin:templates.table.actions')}</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {loading && items.length === 0 && (
                <TableRow><TableCell colSpan={8} sx={{ textAlign: 'center', py: 6 }}>
                  <CircularProgress size={24} />
                </TableCell></TableRow>
              )}
              {!loading && items.length === 0 && (
                <TableRow><TableCell colSpan={8} sx={{ textAlign: 'center', py: 6, color: md.onSurfaceVariant }}>—</TableCell></TableRow>
              )}
              {items.map(tpl => (
                <TableRow key={tpl.slug} hover sx={{ '& td': { borderBottom: `1px solid ${md.outlineVariant}`, whiteSpace: 'nowrap' } }}>
                  <TableCell padding="checkbox">
                    <Checkbox checked={selected.has(tpl.slug)} disabled={tpl.is_default}
                      onChange={(_, c) => toggleOne(tpl.slug, c)} />
                  </TableCell>
                  <TableCell sx={{ fontSize: 13 }}>{tpl.slug}</TableCell>
                  <TableCell sx={{ fontWeight: 500 }}>{tpl.name}</TableCell>
                  <TableCell sx={{ fontSize: 13, color: md.onSurfaceVariant }}>{tpl.client_type}</TableCell>
                  <TableCell sx={{ fontSize: 13, maxWidth: 280, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {ruleSetSummary(tpl)}
                  </TableCell>
                  <TableCell>{coverageBadge(tpl)}</TableCell>
                  <TableCell>
                    {tpl.is_default && badge(t('admin:templates.status.default'), md.primaryContainer, md.onPrimaryContainer)}
                  </TableCell>
                  <TableCell align="right">
                    <Tooltip title={t('admin:templates.field.is_default')}>
                      <IconButton size="small" onClick={() => openEdit(tpl)}><EditIcon fontSize="small" /></IconButton>
                    </Tooltip>
                    <Tooltip title={t('admin:templates.batch_delete')}>
                      <span>
                        <IconButton size="small" onClick={() => confirmDelete(tpl)} disabled={tpl.is_default}
                          sx={{ color: md.error }}>
                          <DeleteIcon fontSize="small" />
                        </IconButton>
                      </span>
                    </Tooltip>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Card>

      {/* Create/Edit dialog */}
      <Dialog open={dialogOpen} onClose={() => !busy && setDialogOpen(false)}
        PaperProps={{ sx: { borderRadius: 3, bgcolor: md.surfaceContainerHigh, width: 900, maxWidth: '95vw' } }}>
        <DialogTitle>
          {editing ? t('admin:templates.edit_title') : t('admin:templates.create')}
        </DialogTitle>
        <DialogContent>
          <Box component="form" id="tpl-form" onSubmit={submit} sx={{ display: 'flex', flexDirection: 'column', gap: 2.5, pt: 1 }}>
            <Box sx={{ display: 'flex', gap: 2 }}>
              <TextField required label={t('admin:templates.field.slug')}
                value={form.slug} disabled={editing}
                onChange={e => setForm({ ...form, slug: e.target.value })}
                sx={{ flex: 1, '& input': {  } }} />
              <TextField required label={t('admin:templates.field.name')}
                value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}
                sx={{ flex: 1 }} />
            </Box>
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center' }}>
              <TextField select size="small" label={t('admin:templates.field.client_type')}
                value={form.client_type}
                onChange={e => setForm({ ...form, client_type: e.target.value })}
                sx={{ minWidth: 220 }}>
                <MenuItem value="mihomo">mihomo</MenuItem>
                <MenuItem value="sing-box">Sing-box</MenuItem>
              </TextField>
              <FormControlLabel
                label={t('admin:templates.field.is_default')}
                control={<Switch checked={form.is_default} onChange={(_, c) => setForm({ ...form, is_default: c })} />}
                sx={{ ml: 1, '& .MuiFormControlLabel-label': { ml: 1.5 } }}
              />
            </Box>
            <Box>
              <FormControl fullWidth size="small">
                <InputLabel shrink>{t('admin:templates.field.rule_sets')}</InputLabel>
                <Select multiple
                  value={form.rule_sets}
                  onChange={e => setForm({ ...form, rule_sets: e.target.value as string[] })}
                  input={<OutlinedInput notched label={t('admin:templates.field.rule_sets')} />}
                  displayEmpty
                  renderValue={(sel) =>
                    (sel as string[]).length === 0
                      ? <Typography sx={{ color: md.onSurfaceVariant, fontSize: 14 }}>{t('admin:templates.placeholder.rule_sets')}</Typography>
                      : (
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                          {(sel as string[]).map(s => {
                            const rs = ruleSetMap.get(s)
                            return <Chip key={s} label={rs?.name || s} size="small" />
                          })}
                        </Box>
                      )}
                >
                  {ruleSets.map(rs => (
                    <MenuItem key={rs.slug} value={rs.slug} disabled={!rs.enabled}>
                      <Checkbox checked={form.rule_sets.includes(rs.slug)} sx={{ mr: 1, p: 0.5 }} />
                      <ListItemText primary={`${rs.name} (${rs.slug})`} />
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
              <Typography sx={{ fontSize: 12, color: md.onSurfaceVariant, mt: 0.5 }}>
                {t('admin:templates.hint.rule_sets')}
              </Typography>
              {hint && (
                <Typography sx={{ fontSize: 12, color: hint.color, mt: 1 }}>{hint.text}</Typography>
              )}
            </Box>
            <TextField fullWidth multiline minRows={14} maxRows={28}
              label={t('admin:templates.field.content')}
              placeholder={t('admin:templates.placeholder.content')}
              value={form.content}
              onChange={e => setForm({ ...form, content: e.target.value })}
              sx={{ '& textarea': { fontSize: 13 } }} />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDialogOpen(false)} disabled={busy} variant="text">{t('common:actions.cancel')}</Button>
          <Button type="submit" form="tpl-form" variant="contained" disabled={busy}
            startIcon={busy ? <CircularProgress size={16} color="inherit" /> : null}>
            {t('common:actions.ok')}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
